# Generated by Django 6.0.5 on 2026-05-25 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                ("slug", models.CharField(max_length=100, verbose_name="Slug")),
                (
                    "icon",
                    models.CharField(
                        default="📌", max_length=10, verbose_name="Ikonka"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Kirim"),
                            ("expense", "Chiqim"),
                            ("both", "Ikkalasi"),
                        ],
                        default="both",
                        max_length=10,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Standart"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="users.telegramuser",
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Kirim"), ("expense", "Chiqim")],
                        max_length=10,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Summa"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("UZS", "So'm"), ("USD", "Dollar"), ("RUB", "Rubl")],
                        default="UZS",
                        max_length=3,
                        verbose_name="Valyuta",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Naqd"),
                            ("card", "Karta"),
                            ("click", "Click"),
                            ("payme", "Payme"),
                            ("bank", "Bank"),
                            ("other", "Boshqa"),
                        ],
                        default="cash",
                        max_length=10,
                        verbose_name="To'lov turi",
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="Izoh")),
                ("transaction_date", models.DateField(verbose_name="Sana")),
                (
                    "raw_text",
                    models.TextField(blank=True, default="", verbose_name="Asl matn"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqt"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transactions.category",
                        verbose_name="Kategoriya",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="users.telegramuser",
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tranzaksiya",
                "verbose_name_plural": "Tranzaksiyalar",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
